### ISSUE TITLE
Sync gitmojis with carloscuesta/gitmoji

### ISSUE THREAD

**Issue by kevtan** [seatonjiang/gitmoji-vscode#14]
Hi @seatonjiang! I was just wondering if it might be possible to periodically sync emojis + descriptions from the carloscuesta/gitmoji repository? As time goes on this VSCode version of gitmoji (this) will diverge more and more from the "central" repository which I think is carloscuesta/gitmoji. Let me know what you think! If you think it's a good idea we can work on implementing it!

**Comment by seatonjiang** [comment]
Hi @kevtan ,

I've realised this and am currently thinking about how to automate the process of pulling the official updates, as you say I've just synced the official updates, but for now I'm just going to have to do this manually. So there's no guarantee of timeliness. Just like this commit：https://github.com/vtrois/gitmoji-vscode/commit/8e4fedcc93d17ee1967af939670674ec6f618a23

The automation is simple, just sync vtrois/gitmoji-vscode `src/gitmoji/gitmoji.ts` and carloscuesta/gitmoji `/src/data/gitmojis.json`.

Hopefully we can exchange a great solution.

**Comment by seatonjiang** [comment]
As you know, in recent months, because of COVID-19, I've been doing a lot of offline stuff, like volunteering at hospitals, so I didn't take care of this project.

**Comment by kevtan** [comment]
Hey @seatonjiang ! No worries. I was out for a few days myself but now I'm back. I'm not very familiar with writing VS Code extensions (looking into it right now) so I'd have to do more research before giving concrete suggestions on a good syncing process. Ideally, we'd want changes to propagate more or less immediately after they appear in carloscuesta/gitmoji, right? Have you thought about merging this project into the official repository?

**Comment by seatonjiang** [comment]
@kevtan I thought the official repository was a specification. We can manually agree on an update cycle, say 1-2 weeks to sync and update the plugin version once.

**Comment by seatonjiang** [comment]
Through long-term observation, the official update speed of gitmoji is not very fast, so it is not a problem to synchronize with it manually once in 1-2 weeks.

**Comment by seatonjiang** [comment]
After two years of updates, nothing much has changed in carloscuesta/gitmoji, so manual synchronization is appropriate for this project.
