### ISSUE TITLE
Add Powershell/Terminal Support/AutoComplete for Gitmoji

### ISSUE THREAD

**Issue by Prathamesh-Shanbhag** [seatonjiang/gitmoji-vscode#31]
I am assuming the Extension only works when making commits through VSCode so please add Terminal support

**Comment by sercanuste** [comment]
Hi @Prathamesh-Shanbhag. You can use [carloscuesta/gitmoji-cli](https://github.com/carloscuesta/gitmoji-cli).

**Comment by seatonjiang** [comment]
Hi @Prathamesh-Shanbhag 

As @sercanuste said, to use Gitmoji in Powershell/Terminal, use the project https://github.com/carloscuesta/gitmoji-cli
