### ISSUE TITLE
Update Open VSX registry version

### ISSUE THREAD

**Issue by andywampir** [seatonjiang/gitmoji-vscode#37]
Please update version of your useful extension in [open-vsx](https://open-vsx.org) registry

**Comment by identithree** [comment]
Bump.

**Comment by seatonjiang** [comment]
Hi @andywampir @identithree 

The version on Open VSX has been updated, and subsequent updates will be automatically synchronized.

https://open-vsx.org/extension/seatonjiang/gitmoji-vscode
