### ISSUE TITLE
On VSCode 1.69 and 1.70 with enabled Command Center, Gitmoji emoji lists pop-up got broken

### ISSUE THREAD

**Issue by gusbemacbe** [seatonjiang/gitmoji-vscode#39]
Hello @seatonjiang !

Notice:

![Gitmoji Bug](https://user-images.githubusercontent.com/2257024/178891474-569fecca-cb75-44c8-b220-89582910373c.gif)

**Comment by seatonjiang** [comment]
Hi @gusbemacbe 

Please check if `gitmoji.onlyUseAdditionalEmojis` is true (`gitmoji.onlyUseCustomEmoji` in the new version), or update Gitmoji 1.2.0, everything works fine in my local tests.

**Comment by AntoineKM** [comment]
same issue for me

**Comment by seatonjiang** [comment]
Hi @gusbemacbe @AntoineKM 

Please update your VSCode version (greater than 1.73.0) and use the latest version of Gitmoji (v1.2.0) and try to see if the problem still occurs.

**Comment by gusbemacbe** [comment]
Hi @seatonjiang 

I apologise for my long absence. I have been overworking. 

I have tested:

- without Command Centre:

   ![image](https://user-images.githubusercontent.com/2257024/205527706-e7907e0e-88ba-40ba-881b-6a9c414080cc.png)

- with Command Centre:

   ![image](https://user-images.githubusercontent.com/2257024/205527862-6e0c1806-ad56-4bd5-956f-6d375bb3ac98.png)

Both worked.

**Comment by gusbemacbe** [comment]
I switched VSCode's language and noticed Gitmoji icon disappeared from Source Control:

![image](https://user-images.githubusercontent.com/2257024/205528361-4fe92636-f7fc-4031-9aee-68bb16f1e442.png)

**Comment by seatonjiang** [comment]
Hi @gusbemacbe 

Gitmoji icons are displayed in the Source Manager instead of the Extension Manager.

![image](https://user-images.githubusercontent.com/57834639/206050223-bd623703-b41f-472c-a0a3-4cdb9549a116.png)

**Comment by seatonjiang** [comment]
Hi @gusbemacbe 

Is this problem solved? I'll close this issues for now, if not solved, please reopen it.
