### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'path')

### ISSUE THREAD

**Issue by r4f4siqueira** [seatonjiang/gitmoji-vscode#44]
### This is the output i got from vscode `Extension Host`
![image](https://user-images.githubusercontent.com/51487888/206294377-07279cb3-2911-4f63-9311-cfb980ce7f95.png)

**Comment by YounesBessa** [comment]
I have the same issue

**Comment by AntoineKM** [comment]
I confirm that it does not work with version 1.74!

**Comment by r4f4siqueira** [comment]
I updated to v1.2.2 and it worked perfectly!
Thank you!😆
