### ISSUE TITLE
🐛 bug: `command 'extension.showGitmoji' not found` on version 1.2.0

### ISSUE THREAD

**Issue by thlmenezes** [seatonjiang/gitmoji-vscode#45]
Using the vscode extension on version v1.1.2 works as expects, however upgrading to the latest version 1.2.0 introduces a bug as I click the show gitmoji button on the Version Control Tab in UI.

Sending video on imgur to help with debugging: https://imgur.com/a/cpcdvLl

## VSCode about

![image](https://user-images.githubusercontent.com/33532177/209470116-666e417d-e7cb-4e79-9354-dbc17a847152.png)

**Comment by seatonjiang** [comment]
Hi @thlmenezes 
Please update to v1.2.2 and try again. In addition, you need to update VSCode to the latest version.

**Comment by thlmenezes** [comment]
Tested the update on the newest vscode insiders version and works like a charm, closing issue.

![image](https://user-images.githubusercontent.com/33532177/209470146-dcddd2c7-dfa8-4ee6-8353-335e00014eb6.png)

Thanks for the quick reply
