### ISSUE TITLE
Coding while baked 🌳

### ISSUE THREAD

**Issue by akzana** [seatonjiang/gitmoji-vscode#66]
I notice there is a 'been coding while drunk 🍻'.
Could we have one for 'coding while baked 🌳'?
thx
search tags
weed
cannabis
stoned
baked

**Comment by seatonjiang** [comment]
The code is synchronized with the Gitmoji library, a requirement that can be customized and added, similar to that of the

```
{
  "gitmoji.addCustomEmoji": [
    {
      "emoji": "🌳",
      "code": ":thread:",
      "description": "coding while baked"
    }
  ]
}
```

**Comment by akzana** [comment]
Awesome! Thanks for sharing
